### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by briangershon** [pbteja1998/nextjs-starter#3]
Hi @pbteja1998, nice work on your starter!

I'm particularly interested in giving your FaunaDB adapter a try, but unclear what your code license is.

Would you mind adding a license to this repo?

(Will it be the same licensing as the new repo that @balazsorban44 created at https://github.com/nextauthjs/adapters?)

Thank you!

**Comment by pbteja1998** [comment]
Hi, i took the code of the adapter from some of the PRs in next-auth repository. I will be adding the same code to the https://github.com/nextauthjs/adapters soon and make it as a package. I will be removing this code from this repo and use that package. Please give me some time to do this. I will also add the license by then.

**Comment by pbteja1998** [comment]
Added the license.
