### ISSUE TITLE
How to setup login? - It gets stuck on loading

### ISSUE THREAD

**Issue by dlogvin** [pbteja1998/nextjs-starter#7]
Basically what the title says. I have put the SMTP details, Fauna is already running, but I just click on sign-in with email... and it just gets stuck on loading.

How to set it up?

**Comment by pbteja1998** [comment]
Hey, can you tell me all the steps that you performed, and also please tell me if you are using Fauna Docker or using Fauna Cloud.

**Comment by dlogvin** [comment]
Sorry for the late response, didn't receive the notification. 

Well, I added my mailgun SMTP credentials, I click login, and nothing. 

I'm making use of Fauna Docker.

**Comment by pbteja1998** [comment]
Hey @dlogvin, I made a few changes in the template very recently. Can you please use the latest version, and follow the instructions in README, and see if you still face the problems.

For your reference, someone else also used Fauna Docker recently. Checkout the issue at #9 and see if any of it helps.

Please let me know if you still face any problems after this.

**Comment by dlogvin** [comment]
Hello, I'm getting an `error Command "setup-docker-db" not found.

**Comment by pbteja1998** [comment]
You might be using the old version then. Download the current version of the template.

**Comment by dlogvin** [comment]
Sure, let me try

**Comment by pbteja1998** [comment]
@dlogvin were you able to resolve your problem?

**Comment by dlogvin** [comment]
I'm sorry. I'll try today, academic pressure... 🥲

**Comment by dlogvin** [comment]
For some reason I'm being redirected to about:blank#blocked when I click on any login button

**Comment by dlogvin** [comment]
Okay, after commenting the line of the `NEXTAUTH_URL` I got it working.

Thank you for updatign, I submitted a pull request
